fixtures:
  repositories:
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    vcsrepo:
      repo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo.git'
    apache:
      repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
  symlinks:
    reposado: "#{source_dir}"
